// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type FormerName struct {
	ID                 int64
	Name               sql.NullString
	NotificationEmails sql.NullString
	LastChecked        sql.NullTime
	LastUpdatedStatus  sql.NullTime
	Status             sql.NullString
}

type User struct {
	ID             int64
	Email          string
	HashedPassword []byte
}

type UserSession struct {
	ID      string
	UserID  string
	Created interface{}
}
